In [79]:
import pandas as pd

In [80]:
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df1=pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [81]:
####1.display top 3 rows of the dataset

In [82]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

In [83]:
####2.Check last 3 rows of the dataset

In [84]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [85]:
#### 3.Shape of the dataset

In [86]:
df1.shape

(7, 3)

In [87]:
print('Number of rows ',df1.shape[0])
print('Number of columns ',df1.shape[1])

Number of rows  7
Number of columns  3

In [88]:
#### 4. info about our dataset like total nimber of rows, total number of olumns, data types and memory requirement

In [89]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [90]:
#####  5. checking null values

In [91]:
df1.isnull().sum(axis = 1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [92]:
##########3336. over alll sttistics

In [93]:
df1.describe(include = 'all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [94]:
#############unique v values from gender

In [95]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [96]:
df1["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [97]:
##8 unoque values from gender

In [98]:
df1["Gender"].nunique()

2

In [99]:
###9. count of unique value from gender

In [100]:
df1["Gender"].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [101]:
#10  total number of students having marks having between 90 and 100

In [102]:
df1[(df1["Marks"] >= 90) & (df1["Marks"]  <= 100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [103]:
# avg of marks

In [104]:
df1["Marks"].mean()

np.float64(92.14285714285714)

In [105]:
##apply method

In [106]:
def marks(x):
    return x/2

In [107]:
df1["Half_marks"]= df1["Marks"].apply(marks)
df1

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   Krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [108]:
#######  map function

In [109]:
df1["Gender_updared"] = df1["Gender"].map({"Male": 1,"Female":0})

In [110]:
df1

      Name  Marks  Gender  Half_marks  Gender_updared
0  Priyang     98    Male        49.0               1
1   Aadhya     89  Female        44.5               0
2   Krisha     99  Female        49.5               0
3   Vedant     87    Male        43.5               1
4   Parshv     90    Male        45.0               1
5   Mittal     83  Female        41.5               0
6  Archana     99  Female        49.5               0

In [111]:
########drop

In [112]:
df1.drop(["Half_marks", "Gender_updared"],axis = 1,inplace = True)

In [113]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [114]:
#########print cloumns names

In [115]:
df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [117]:
df1.index

RangeIndex(start=0, stop=7, step=1)

In [118]:
##sort marks colum

In [119]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [123]:
df1.sort_values(by =["Marks","Gender"], ascending = False)

      Name  Marks  Gender
2   Krisha     99  Female
6  Archana     99  Female
0  Priyang     98    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

In [124]:
###display  name & marks of the female students

In [130]:
df1[df1["Gender"] == 'Female'][["Name","Marks"]]

      Name  Marks
1   Aadhya     89
2   Krisha     99
5   Mittal     83
6  Archana     99